# Generated by Django 4.2.3 on 2023-07-11 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project_website', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usermodel',
            name='fullname',
        ),
        migrations.AddField(
            model_name='usermodel',
            name='firstname',
            field=models.CharField(default='___', max_length=100),
        ),
        migrations.AddField(
            model_name='usermodel',
            name='lastname',
            field=models.CharField(default='___', max_length=100),
        ),
        migrations.AlterField(
            model_name='usermodel',
            name='phone',
            field=models.CharField(default='___', max_length=100),
        ),
        migrations.AlterField(
            model_name='usermodel',
            name='r_address',
            field=models.CharField(default='___', max_length=100),
        ),
        migrations.AlterField(
            model_name='usermodel',
            name='r_name',
            field=models.CharField(default='___', max_length=100),
        ),
        migrations.AlterField(
            model_name='usermodel',
            name='r_number',
            field=models.CharField(default='___', max_length=100),
        ),
    ]
